/**
 * Client-side encryption using the Web Crypto API.
 *
 * Provides AES-256-GCM encryption for file chunks using a key
 * derived from a user password via PBKDF2.
 *
 * Security design:
 * - Password is never sent to the server (not even hashed)
 * - Key is derived client-side: PBKDF2(password, salt, 100000, SHA-256) → AES-256
 * - Each chunk uses a unique 12-byte random IV (prevents ciphertext analysis)
 * - IV is prepended to the ciphertext: [12-byte IV][ciphertext + 16-byte GCM tag]
 * - The salt is generated by the sender and included in the file metadata message
 *   (sent via DataChannel, not through the server)
 *
 * See SRS.md §FR-12, FR-13 for requirements.
 * See BRD.md §BR-03 for the password privacy requirement.
 * See frontend-doc.md §6.2 for integration in transfer.js.
 *
 * @module crypto
 */

export const SALT_LENGTH = 16    // bytes
export const IV_LENGTH = 12      // bytes (AES-GCM standard)
const KEY_LENGTH = 256           // bits (AES-256)
const PBKDF2_ITERATIONS = 100000

/**
 * Generate a random salt for key derivation.
 * The sender generates this and includes it in the file metadata message.
 *
 * @returns {Uint8Array} 16 random bytes
 */
export function generateSalt() {
    return crypto.getRandomValues(new Uint8Array(SALT_LENGTH))
}

/**
 * Derive an AES-256-GCM key from a password using PBKDF2.
 *
 * This function uses 100,000 PBKDF2 iterations with SHA-256.
 * Calling this with the same password + salt always produces the same key.
 * This is how sender and receiver derive the same key without sharing it.
 *
 * @param {string} password - User-provided password
 * @param {Uint8Array} salt - Random salt (generated by sender, shared in metadata)
 * @returns {Promise<CryptoKey>} AES-GCM key ready for encrypt/decrypt
 */
export async function deriveKey(password, salt) {
    const encoder = new TextEncoder()
    const passwordBuffer = encoder.encode(password)

    // Step 1: Import the raw password as a key material
    const keyMaterial = await crypto.subtle.importKey(
        'raw',
        passwordBuffer,
        'PBKDF2',
        false,
        ['deriveKey']
    )

    // Step 2: Derive the AES-GCM key via PBKDF2
    return crypto.subtle.deriveKey(
        {
            name: 'PBKDF2',
            salt: salt,
            iterations: PBKDF2_ITERATIONS,
            hash: 'SHA-256',
        },
        keyMaterial,
        { name: 'AES-GCM', length: KEY_LENGTH },
        true,        // exportable (needed for testing)
        ['encrypt', 'decrypt']
    )
}

/**
 * Encrypt an ArrayBuffer chunk using AES-256-GCM.
 *
 * Output format: [12-byte IV][AES-GCM ciphertext + 16-byte auth tag]
 * Total overhead: 28 bytes per chunk (IV + GCM tag)
 *
 * @param {ArrayBuffer} plaintext - Raw chunk data
 * @param {CryptoKey} key - Derived AES-GCM key
 * @returns {Promise<ArrayBuffer>} Encrypted data with prepended IV
 */
export async function encryptChunk(plaintext, key) {
    // Generate a unique IV for each chunk — NEVER reuse IVs with the same key
    const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH))

    const ciphertext = await crypto.subtle.encrypt(
        { name: 'AES-GCM', iv },
        key,
        plaintext
    )

    // Prepend IV: [12 bytes IV][ciphertext]
    const result = new Uint8Array(IV_LENGTH + ciphertext.byteLength)
    result.set(iv, 0)
    result.set(new Uint8Array(ciphertext), IV_LENGTH)
    return result.buffer
}

/**
 * Decrypt an ArrayBuffer chunk using AES-256-GCM.
 *
 * Expects the same format as encryptChunk output:
 * [12-byte IV][AES-GCM ciphertext + 16-byte auth tag]
 *
 * Throws DOMException if decryption fails (wrong key or tampered data).
 *
 * @param {ArrayBuffer} data - Encrypted chunk with prepended IV
 * @param {CryptoKey} key - Derived AES-GCM key
 * @returns {Promise<ArrayBuffer>} Decrypted plaintext
 */
export async function decryptChunk(data, key) {
    const dataView = new Uint8Array(data)

    // Extract IV from the first 12 bytes
    const iv = dataView.slice(0, IV_LENGTH)
    const ciphertext = dataView.slice(IV_LENGTH).buffer

    return crypto.subtle.decrypt(
        { name: 'AES-GCM', iv },
        key,
        ciphertext
    )
}

/**
 * Convert a Uint8Array salt to a Base64 string for transmission in JSON.
 * @param {Uint8Array} salt
 * @returns {string}
 */
export function saltToBase64(salt) {
    return btoa(String.fromCharCode(...salt))
}

/**
 * Convert a Base64 string back to a Uint8Array salt.
 * @param {string} b64
 * @returns {Uint8Array}
 */
export function saltFromBase64(b64) {
    return new Uint8Array(atob(b64).split('').map(c => c.charCodeAt(0)))
}
